--- #YAML:1.0
name:               Debian-Packages
version:            0.01
abstract:           An interface to a Debian Packages file
author:
    - Jeremiah C. Foster <jeremiah@cpan.org>
license:            unknown
distribution_type:  module
configure_requires:
    ExtUtils::MakeMaker:  0
requires:
    Moose:         0
    Perl6::Slurp:  0
no_index:
    directory:
        - t
        - inc
generated_by:       ExtUtils::MakeMaker version 6.48
meta-spec:
    url:      http://module-build.sourceforge.net/META-spec-v1.4.html
    version:  1.4
